### ISSUE TITLE
FastCGI

### ISSUE THREAD

**Issue by rwhaling** [scala-native/scala-native-loop#6]
Even with a proper, compliant parser, this server is still a small fraction of what needs to be done to be a full, robust, internet-ready public-facing HTTP server.  Rather than bite off that enormous task, we can use FastCGI for low-overhead streaming with a gateway service - Nginx has good support, and I've had some success implementing it here:

https://github.com/rwhaling/dinosaur

Let's port this to LibUV and make it a configurable flag of Service.run()

**Comment by lolgab** [comment]
Superseded by https://github.com/lolgab/snunit which works on top of scala-native-loop
